// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.Infrastructure.Persistence;

#nullable disable

namespace StudentManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325105826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagement.Domain.Entities.DangKyHoc", b =>
                {
                    b.Property<int>("DangKyHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DangKyHocId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Diem")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("HocKyId")
                        .HasColumnType("int");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Chua co diem");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DangKyHocId");

                    b.HasIndex("HocKyId");

                    b.HasIndex("MonHocId");

                    b.HasIndex("SinhVienId", "MonHocId", "HocKyId")
                        .IsUnique();

                    b.ToTable("DangKyHoc", null, t =>
                        {
                            t.HasCheckConstraint("CK_DangKyHoc_Diem", "Diem IS NULL OR (Diem >= 0 AND Diem <= 10)");
                        });
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.GiangVien", b =>
                {
                    b.Property<int>("GiangVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiangVienId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("KhoaId")
                        .HasColumnType("int");

                    b.Property<string>("MaGiangVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("GiangVienId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KhoaId");

                    b.HasIndex("MaGiangVien")
                        .IsUnique();

                    b.ToTable("GiangVien", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.HocKy", b =>
                {
                    b.Property<int>("HocKyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HocKyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaHocKy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NamHoc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("HocKyId");

                    b.HasIndex("MaHocKy")
                        .IsUnique();

                    b.ToTable("HocKy", null, t =>
                        {
                            t.HasCheckConstraint("CK_HocKy_NamHoc", "NamHoc >= 2000 AND NamHoc <= 2100");

                            t.HasCheckConstraint("CK_HocKy_ThoiGian", "NgayBatDau IS NULL OR NgayKetThuc IS NULL OR NgayBatDau <= NgayKetThuc");
                        });
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.Khoa", b =>
                {
                    b.Property<int>("KhoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhoaId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("TruongKhoaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("KhoaId");

                    b.HasIndex("MaKhoa")
                        .IsUnique();

                    b.HasIndex("TruongKhoaId");

                    b.ToTable("Khoa", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.LopHoc", b =>
                {
                    b.Property<int>("LopHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LopHocId"));

                    b.Property<int?>("CoVanHocTapId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("KhoaId")
                        .HasColumnType("int");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LopHocId");

                    b.HasIndex("CoVanHocTapId");

                    b.HasIndex("KhoaId");

                    b.HasIndex("MaLop")
                        .IsUnique();

                    b.ToTable("LopHoc", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.MonHoc", b =>
                {
                    b.Property<int>("MonHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonHocId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GiangVienGiangDayId")
                        .HasColumnType("int");

                    b.Property<int?>("HocKyId")
                        .HasColumnType("int");

                    b.Property<int?>("KhoaId")
                        .HasColumnType("int");

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MonHocId");

                    b.HasIndex("GiangVienGiangDayId");

                    b.HasIndex("HocKyId");

                    b.HasIndex("KhoaId");

                    b.HasIndex("MaMonHoc")
                        .IsUnique();

                    b.ToTable("MonHoc", null, t =>
                        {
                            t.HasCheckConstraint("CK_MonHoc_SoTinChi", "SoTinChi BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.SinhVien", b =>
                {
                    b.Property<int>("SinhVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinhVienId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("LopHocId")
                        .HasColumnType("int");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SinhVienId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LopHocId");

                    b.HasIndex("MaSinhVien")
                        .IsUnique();

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.DangKyHoc", b =>
                {
                    b.HasOne("StudentManagement.Domain.Entities.HocKy", "HocKy")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagement.Domain.Entities.MonHoc", "MonHoc")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagement.Domain.Entities.SinhVien", "SinhVien")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("MonHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.GiangVien", b =>
                {
                    b.HasOne("StudentManagement.Domain.Entities.Khoa", "Khoa")
                        .WithMany("GiangViens")
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.Khoa", b =>
                {
                    b.HasOne("StudentManagement.Domain.Entities.GiangVien", "TruongKhoa")
                        .WithMany("KhoaLamTruongKhoa")
                        .HasForeignKey("TruongKhoaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TruongKhoa");
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.LopHoc", b =>
                {
                    b.HasOne("StudentManagement.Domain.Entities.GiangVien", "CoVanHocTap")
                        .WithMany("LopHocCoVans")
                        .HasForeignKey("CoVanHocTapId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudentManagement.Domain.Entities.Khoa", "Khoa")
                        .WithMany("LopHocs")
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoVanHocTap");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.MonHoc", b =>
                {
                    b.HasOne("StudentManagement.Domain.Entities.GiangVien", "GiangVienGiangDay")
                        .WithMany("MonHocGiangDays")
                        .HasForeignKey("GiangVienGiangDayId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudentManagement.Domain.Entities.HocKy", "HocKy")
                        .WithMany("MonHocs")
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudentManagement.Domain.Entities.Khoa", "Khoa")
                        .WithMany("MonHocs")
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GiangVienGiangDay");

                    b.Navigation("HocKy");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.SinhVien", b =>
                {
                    b.HasOne("StudentManagement.Domain.Entities.LopHoc", "LopHoc")
                        .WithMany("SinhViens")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.GiangVien", b =>
                {
                    b.Navigation("KhoaLamTruongKhoa");

                    b.Navigation("LopHocCoVans");

                    b.Navigation("MonHocGiangDays");
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.HocKy", b =>
                {
                    b.Navigation("DangKyHocs");

                    b.Navigation("MonHocs");
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.Khoa", b =>
                {
                    b.Navigation("GiangViens");

                    b.Navigation("LopHocs");

                    b.Navigation("MonHocs");
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.LopHoc", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.MonHoc", b =>
                {
                    b.Navigation("DangKyHocs");
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.SinhVien", b =>
                {
                    b.Navigation("DangKyHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
